### ISSUE TITLE
Any idea on opening HDR hybrid event/frame dataset?

### ISSUE THREAD

**Issue by wyang-vis** [ziweiWWANG/AKF#4]
Hi, Thanks for your contribution and your great work. I am curious about the HDR hybrid event/frame dataset, an excellent real-world HDR hybrid event/frame dataset. Do you have any plans to release the dataset? Thanks first.

**Comment by ziweiWWANG** [comment]
Thank you for your inquiry. Currently, I am working on other projects but I intend to release the dataset before June, or possibly even earlier. I will let you know when it is ready and I hope that it will not cause any inconvenience to you.

**Comment by ziweiWWANG** [comment]
Hi there!    
Please find the HDR hybrid event/frame dataset available here: 
https://anu365-my.sharepoint.com/:f:/g/personal/u6456661_anu_edu_au/EnruCV7YMuhGnL1AFcO78S8BXCeLrTde6TE0iwE8hLyUoA?e=vB1uAi
You can also find the link in README.md now. I will provide more instructions soon.

Feel free to let me know if you have any other questions :)

Cheers,
Ziwei
