### ISSUE TITLE
About event refractory period noise, in line 244 of akf_reconstruction.m

### ISSUE THREAD

**Issue by DanyLee19** [ziweiWWANG/AKF#5]
Regarding the event's refractory period noise, I am interested in the fact that in line 244 of akf_reconstruction.m, Q_r is calculated differently than refractory period noise in the paper. The Q_r in the code seems to decrease as the interval between successive triggered events decreases, is this reasonable?

**Comment by ziweiWWANG** [comment]
Hi Dany,

Thanks for your question. You are right that this is a typo in the current version. 
When the time interval is larger than the refectory period, we set the Q_r to zero for no refractory period noise.
When the time interval is smaller than the refectory period, which rarely happens, you can set it to a fixed default value Q_r. You can tune this parameter based on your datasets.

Thank you for pointing it out.

Best regards,
Ziwei

**Comment by DanyLee19** [comment]
Thanks！
